CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  api_key TEXT NOT NULL UNIQUE,
  plan TEXT NOT NULL CHECK (plan IN ('FREE', 'PRO')),
  usage_count INTEGER NOT NULL DEFAULT 0,
  usage_date TEXT NOT NULL
);
